[package]
name = "thunk-rs"
version = "0.1.0"
edition = "2021"
authors = ["felixmaker"]
description = "Thunk the Rust program to support old Windows platforms!"
license = "Apache-2.0 OR MIT"
keywords = ["build-dependencies"]
readme = "README.md"
categories = ["development-tools::build-utils"]
repository = "https://github.com/felixmaker/thunk"
documentation = "https://docs.rs/thunk-rs"

[lib]
name = "thunk"
path = "src/lib.rs"

[dependencies]
